name: 'Terraform'
on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7 
        
      - name: Terraform Init  
        run: terraform init
      - name: terraform validate
        run: terraform validate      
      - name: Terraform Plan
        run: terraform plan -var-file="./environments/dev.tfvars" -out=plan.out
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
      - name: Terraform apply
        run: terraform apply -var-file="./environments/dev.tfvars" -auto-approve
      #- name: Terraform apply
       # run: terraform apply -auto-approve plan.out
        #if: github.ref == 'refs/heads/master' && github.event_name == 'push'


