name: 'Terraform'
on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: DEV
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
         with:
         terraform_version: 1.5.7  
        
      - name: Terraform Init
        run: terraform init
      - name: terraform validate
        run: terraform validate      
      - name: Determine Environment Variables File
        id: env-vars
        run: ./environments/dev.tfvars
      - name: Terraform Plan
        run: terraform plan -var-file=environments/${{ env.tfvars_file }}
     - name: Terraform apply
        run: terraform apply -var-file="environments/dev.tfvars" -auto-approve

